Please note that the following code is taken from the book "Deep Learning With Python (2nd ed.)" without modifications to accommodate the lectures on "Introduction to Machine Learning", which is a part of the course CSI4106 "Introduction to Artificial Intelligence" taught in Winter 2022.

Chollet, F. (2021). Deep Learning With Python (2nd ed.). Manning Publications.

Please do not redistribute the code.

In [22]:
import pandas as pd
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist
import os
import datetime

%reload_ext tensorboard
%tensorboard --logdir logs

Reusing TensorBoard on port 6006 (pid 78548), started 5:20:36 ago. (Use '!kill 78548' to kill it.)

In [23]:
inputs = keras.Input(shape=(28, 28, 1)) 
x = layers.Conv2D(filters=32, kernel_size=3, activation="relu")(inputs) 
x = layers.MaxPooling2D(pool_size=2)(x) 
x = layers.Conv2D(filters=64, kernel_size=3, activation="relu")(x) 
x = layers.MaxPooling2D(pool_size=2)(x) 
x = layers.Conv2D(filters=128, kernel_size=3, activation="relu")(x) 
x = layers.Flatten()(x)
outputs = layers.Dense(10, activation="softmax")(x) 
model = keras.Model(inputs=inputs, outputs=outputs)

model.summary()

# padding calculations
# n: image dimension
# f: filter size
# p: padding size
# valid padding -> n - f + 1
# same padding -> n + 2p - f + 1

Model: "model_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 28, 28, 1)]       0         
_________________________________________________________________
conv2d_15 (Conv2D)           (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_10 (MaxPooling (None, 13, 13, 32)        0         
_________________________________________________________________
conv2d_16 (Conv2D)           (None, 11, 11, 64)        18496     
_________________________________________________________________
max_pooling2d_11 (MaxPooling (None, 5, 5, 64)          0         
_________________________________________________________________
conv2d_17 (Conv2D)           (None, 3, 3, 128)         73856     
_________________________________________________________________
flatten_5 (Flatten)          (None, 1152)              0   

In [24]:
print(np.random.rand(26, 26, 32))

[[[0.45087596 0.0046847  0.9264323  ... 0.4521996  0.38673903 0.74936778]
  [0.69799005 0.40796137 0.1780329  ... 0.3274054  0.14383865 0.67132004]
  [0.78822305 0.60599902 0.67265502 ... 0.82506488 0.52205215 0.78623995]
  ...
  [0.34727419 0.40990477 0.69379104 ... 0.8432671  0.72062239 0.89038068]
  [0.36520138 0.33202647 0.08047898 ... 0.8076438  0.53903347 0.32920219]
  [0.10923562 0.8516995  0.27886191 ... 0.83192667 0.43480144 0.72537666]]

 [[0.62741201 0.69391279 0.58905078 ... 0.08954091 0.19410649 0.34113508]
  [0.27238047 0.46633361 0.22637701 ... 0.25662755 0.2195154  0.17279956]
  [0.60311187 0.74123559 0.93843873 ... 0.43422103 0.88574972 0.57497789]
  ...
  [0.54956457 0.44188399 0.7888398  ... 0.57340041 0.39595431 0.21888415]
  [0.22465213 0.8170778  0.82347829 ... 0.87336224 0.46485136 0.86146801]
  [0.21950396 0.2429692  0.05673666 ... 0.2204199  0.99197829 0.48315353]]

 [[0.64220805 0.85077874 0.7934381  ... 0.73605073 0.92820505 0.39847108]
  [0.28641034 0.978156

In [25]:
d = datetime.datetime.today()
timestamp = d.strftime('%Y%m%d_%H%M%S')
tensorlog_folder = os.path.join(os.path.curdir, 'logs', timestamp)
os.mkdir(tensorlog_folder)

tensorboard = keras.callbacks.TensorBoard(log_dir=tensorlog_folder)

2022-02-16 17:24:27.517706: I tensorflow/core/profiler/lib/profiler_session.cc:136] Profiler session initializing.
2022-02-16 17:24:27.517742: I tensorflow/core/profiler/lib/profiler_session.cc:155] Profiler session started.
2022-02-16 17:24:27.517779: I tensorflow/core/profiler/lib/profiler_session.cc:172] Profiler session tear down.


In [26]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data() 
train_images = train_images.reshape((60000, 28, 28, 1)) 
train_images = train_images.astype("float32") / 255 
test_images = test_images.reshape((10000, 28, 28, 1)) 
test_images = test_images.astype("float32") / 255 

model.compile(optimizer="rmsprop", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

model.fit(train_images, train_labels, epochs=3, batch_size=64, callbacks=[tensorboard])

Epoch 1/3
  3/938 [..............................] - ETA: 1:44 - loss: 2.2844 - accuracy: 0.1102

2022-02-16 17:24:29.035447: I tensorflow/core/profiler/lib/profiler_session.cc:136] Profiler session initializing.
2022-02-16 17:24:29.035490: I tensorflow/core/profiler/lib/profiler_session.cc:155] Profiler session started.
2022-02-16 17:24:29.149522: I tensorflow/core/profiler/lib/profiler_session.cc:71] Profiler session collecting data.
2022-02-16 17:24:29.152656: I tensorflow/core/profiler/lib/profiler_session.cc:172] Profiler session tear down.
2022-02-16 17:24:29.158263: I tensorflow/core/profiler/rpc/client/save_profile.cc:137] Creating directory: ./logs/20220216_172427/train/plugins/profile/2022_02_16_17_24_29
2022-02-16 17:24:29.159657: I tensorflow/core/profiler/rpc/client/save_profile.cc:143] Dumped gzipped tool data for trace.json.gz to ./logs/20220216_172427/train/plugins/profile/2022_02_16_17_24_29/pop-os.trace.json.gz
2022-02-16 17:24:29.172214: I tensorflow/core/profiler/rpc/client/save_profile.cc:137] Creating directory: ./logs/20220216_172427/train/plugins/profile/202

938/938 [==============================] - 51s 53ms/step - loss: 0.3341 - accuracy: 0.8927
Epoch 2/3
938/938 [==============================] - 49s 52ms/step - loss: 0.0475 - accuracy: 0.9855
Epoch 3/3
938/938 [==============================] - 44s 47ms/step - loss: 0.0307 - accuracy: 0.9901


In [27]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test accuracy: {test_acc}")

313/313 [==============================] - 1s 3ms/step - loss: 0.0250 - accuracy: 0.9916
test accuracy: 0.991599977016449
